apiVersion: v1
kind: DeploymentConfig
metadata:
  name: drupal-8-db
  labels:
    app: drupal-8  
spec:
  replicas: 1
  selector:
    name: drupal-8-db
    app: drupal-8    
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: drupal-8-db
        app: drupal-8  
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: drupal-8
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: drupal-8
        - name: POSTGRESQL_DATABASE
          value: drupal8
        image: ' '
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: drupal-8-db-data
      volumes:
      - name: drupal-8-db-data
        persistentVolumeClaim:
          claimName: drupal-8-db
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: postgresql:10
        namespace: openshift
    type: ImageChange
  - type: ConfigChange