apiVersion: v1
kind: Service
metadata:
  name: drupal-8-db
  labels:
    app: drupal-8
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: drupal-8-db
    app: drupal-8